<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sabari" failures="0" tests="1" name="Default test" time="0.034" errors="0" timestamp="2022-10-29T12:56:24 IST">
  <testcase classname="com.financeDomain.adfdatafinance.GenericLibraries.BaseClass" name="@BeforeSuite configBS" time="0.389">
    <failure type="java.sql.SQLSyntaxErrorException" message="Unknown database &amp;apos;testing&amp;apos;">
      <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeSuite configBS -->
  <testcase classname="com.financeDomain.adfdatafinance.GenericLibraries.BaseClass" name="@BeforeMethod openApp" time="-1.667028384799E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod openApp -->
  <testcase classname="com.financeDomain.adfdatafinance.GenericLibraries.BaseClass" name="@AfterMethod closeApp" time="-1.667028384809E9">
    <skipped/>
  </testcase> <!-- @AfterMethod closeApp -->
  <testcase classname="com.financeDomain.adfdatafinance.Scripts.TestCase1" name="testcase1" time="0.0">
    <skipped/>
  </testcase> <!-- testcase1 -->
</testsuite> <!-- Default test -->
