<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="10" total="20" passed="0" failed="0" skipped="10">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-30T09:30:57 IST" name="Suite" finished-at="2022-10-30T09:30:58 IST" duration-ms="853">
    <groups>
    </groups>
    <test started-at="2022-10-30T09:30:57 IST" name="Test" finished-at="2022-10-30T09:30:58 IST" duration-ms="853">
      <class name="com.financeDomain.adfdatafinance.Scripts.TestCase5">
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase5@4f18837a]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458496" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase5()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase5@4f18837a]" started-at="2022-10-30T09:30:58 IST" name="testcase5" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase5 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase5@4f18837a]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458501" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.financeDomain.adfdatafinance.Scripts.TestCase5 -->
      <class name="com.financeDomain.adfdatafinance.Scripts.TestCase4">
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase4@6356695f]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458492" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase4()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase4@6356695f]" started-at="2022-10-30T09:30:58 IST" name="testcase4" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase4@6356695f]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458495" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.financeDomain.adfdatafinance.Scripts.TestCase4 -->
      <class name="com.financeDomain.adfdatafinance.Scripts.TestCase6">
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase6@359f7cdf]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458503" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase6()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase6@359f7cdf]" started-at="2022-10-30T09:30:58 IST" name="testcase6" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase6 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase6@359f7cdf]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458508" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.financeDomain.adfdatafinance.Scripts.TestCase6 -->
      <class name="com.financeDomain.adfdatafinance.Scripts.TestCase1">
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase1@1fa268de]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458510" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase1()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase1@1fa268de]" started-at="2022-10-30T09:30:58 IST" name="testcase1" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase1@1fa268de]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458518" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.financeDomain.adfdatafinance.Scripts.TestCase1 -->
      <class name="com.financeDomain.adfdatafinance.Scripts.TestCase3">
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase3@5ffead27]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458486" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase3()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase3@5ffead27]" started-at="2022-10-30T09:30:58 IST" name="testcase3" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase3@5ffead27]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458490" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.financeDomain.adfdatafinance.Scripts.TestCase3 -->
      <class name="com.financeDomain.adfdatafinance.Scripts.TestCase2">
        <test-method is-config="true" signature="configBS()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:57 IST" name="configBS" finished-at="2022-10-30T09:30:57 IST" duration-ms="488" status="FAIL">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458435" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase2(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="testcase2" data-provider="readExceldata" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ramesh]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ramesh@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Selenium]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[test request plz don't consider]]>
              </value>
            </param>
          </params>
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458443" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458446" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase2(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="testcase2" data-provider="readExceldata" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[likith]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[likith@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[java]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[test request plz don't consider]]>
              </value>
            </param>
          </params>
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458460" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458461" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase2(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="testcase2" data-provider="readExceldata" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[sarath]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[saran@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[python]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[test request plz don't consider]]>
              </value>
            </param>
          </params>
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458464" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458466" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase2(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="testcase2" data-provider="readExceldata" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[saran]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sad12@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[.net]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[test request plz don't consider]]>
              </value>
            </param>
          </params>
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458474" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="openApp()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="openApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458476" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testcase2(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="testcase2" data-provider="readExceldata" finished-at="2022-10-30T09:30:58 IST" duration-ms="0" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[saravanan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[saravanan123@gmai.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[java script]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[test request plz don't consider]]>
              </value>
            </param>
          </params>
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'testing']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'testing'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at com.financeDomain.adfdatafinance.GenericLibraries.FileUtilities.getDataDb(FileUtilities.java:79)
at com.financeDomain.adfdatafinance.GenericLibraries.BaseClass.configBS(BaseClass.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="closeApp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458479" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="configAS()[pri:0, instance:com.financeDomain.adfdatafinance.Scripts.TestCase2@7c729a55]" started-at="2022-10-30T09:30:58 IST" name="configAS" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1667102458648" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- com.financeDomain.adfdatafinance.Scripts.TestCase2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
